baseURL: "http://sailorllm.github.io/"
title: Sailor
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

ignoreErrors: ["error-remote-getjson"]

# googleAnalytics: UA-123-45
googleAnalytics: G-BP9G7L138H

defaultContentLanguage: en
languages:
  en:
    languageName: English
    weight: 1
  # zh:
  #   languageName: 简体中文
  #   weight: 2
  #   params:
  #     date_format: "2006年1月2日"


minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Sailor
  description: "Sailor"
  keywords: ["multi-modal", "machine learning", "blog"]
  author: Sailor Team
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]

  # custom site variables
  date_format: "January 2, 2006"
  default_theme: light # dark, light
  disable_theme_toggle: true
  disable_special_first_post: false
  disable_scroll_to_top: false
  displayFullLangName: true

  # custom site and page variables
  show_share_buttons: true
  show_bread_crumbs: true
  hide_meta: false
  math: false
  
  # single page only
  show_code_copy_buttons: true
  show_word_count: true
  use_hugo_toc: true
  show_toc: false
  toc_open: false
  comments: false
  show_reading_time: true
  show_post_nav_links: false
  
  # list page only
  hide_summary: false
  show_rss_button_in_section_term_list: false

  assets:
    disable_hljs: true # to disable highlight.js
    disable_fingerprinting: false
    disable_scroll_bar_style: false

    favicon: /img/sailor-logo.png

  label:
    text: "Sailor"
    # icon: /img/sailor-logo.png
#     icon_svg: '<svg 
#    width="41.687111mm"
#    height="37.703426mm"
#    viewBox="0 0 41.687111 37.703426"
#    version="1.1"
#    id="svg5"
#    xmlns:xlink="http://www.w3.org/1999/xlink"
#    xmlns="http://www.w3.org/2000/svg"
#    xmlns:svg="http://www.w3.org/2000/svg">
#   <defs
#      id="defs2">
#     <linearGradient
#        id="linearGradient3999">
#       <stop
#          style="stop-color:#0000ff;stop-opacity:0.67479676;"
#          offset="0.16"
#          id="stop3995" />
#       <stop
#          style="stop-color:#000000;stop-opacity:0;"
#          offset="1"
#          id="stop3997" />
#     </linearGradient>
#     <linearGradient
#        id="linearGradient3945">
#       <stop
#          style="stop-color:#00ff00;stop-opacity:0.67479676;"
#          offset="0.16"
#          id="stop3941" />
#       <stop
#          style="stop-color:#000000;stop-opacity:0;"
#          offset="1"
#          id="stop3943" />
#     </linearGradient>
#     <linearGradient
#        id="linearGradient3902">
#       <stop
#          style="stop-color:#ff0000;stop-opacity:0.67479676;"
#          offset="0.16"
#          id="stop3898" />
#       <stop
#          style="stop-color:#000000;stop-opacity:0;"
#          offset="1"
#          id="stop3900" />
#     </linearGradient>
#     <radialGradient
#        xlink:href="#linearGradient3902"
#        id="radialGradient3904"
#        cx="61.55265"
#        cy="90.307182"
#        fx="61.55265"
#        fy="90.307182"
#        r="21.788235"
#        gradientUnits="userSpaceOnUse"
#        gradientTransform="matrix(1.0083361,0,0,0.97200857,0.08213891,3.8855297)" />
#     <radialGradient
#        xlink:href="#linearGradient3945"
#        id="radialGradient3904-5"
#        cx="61.55265"
#        cy="90.307182"
#        fx="61.55265"
#        fy="90.307182"
#        r="21.788235"
#        gradientUnits="userSpaceOnUse"
#        gradientTransform="matrix(1,0,0,0.99427089,30.91008,20.549678)" />
#     <radialGradient
#        xlink:href="#linearGradient3999"
#        id="radialGradient3904-5-0"
#        cx="61.55265"
#        cy="90.307182"
#        fx="61.55265"
#        fy="90.307182"
#        r="21.788235"
#        gradientUnits="userSpaceOnUse"
#        gradientTransform="translate(1.2194985,37.034278)" />
#   </defs>
#   <g
#      id="layer1"
#      transform="translate(-52.088293,-91.487792)">
#     <path
#        id="path3871-7"
#        style="fill:url(#radialGradient3904-5);fill-opacity:1;stroke:none;stroke-width:1.59542;stroke-linejoin:round;stroke-dasharray:none;stroke-opacity:1"
#        d="m 83.472675,91.487792 a 20.988234,20.867992 0 0 0 -11.998234,18.851448 20.988234,20.867992 0 0 0 11.998234,18.85198 l 10.30273,-18.85198 z" />
#     <path
#        id="path3871-7-8"
#        style="fill:url(#radialGradient3904-5-0);fill-opacity:1;stroke:none;stroke-width:1.6;stroke-linejoin:round;stroke-dasharray:none;stroke-opacity:1"
#        d="m 62.772396,106.3532 a 20.988234,20.988234 0 0 0 -10.408667,2.76624 l -0.275436,0.50694 10.572999,19.45721 h 21.020939 a 20.988234,20.988234 0 0 0 0.07803,-1.74201 20.988234,20.988234 0 0 0 -20.987865,-20.98838 z" />
#     <path
#        id="path3871"
#        style="fill:url(#radialGradient3904);fill-opacity:1;stroke:none;stroke-width:1.58402;stroke-linejoin:round;stroke-dasharray:none;stroke-opacity:1"
#        d="M 62.489152,91.531243 52.256337,109.68384 a 21.163194,20.400744 0 0 0 9.891512,2.3819 21.163194,20.400744 0 0 0 21.163345,-20.400886 21.163194,20.400744 0 0 0 -0.0021,-0.133611 z" />
#     <circle
#        style="fill:none;stroke:#959595;stroke-width:1.6;stroke-linejoin:round;stroke-dasharray:none;stroke-opacity:0.735203"
#        id="path4787"
#        cx="71.982582"
#        cy="108.95269"
#        r="0.80230254" />
#   </g>
# </svg>'
    iconHeight: 35

  # profile-mode
  # profileMode:
  #   enabled: false # needs to be explicitly set
  #   title: ExampleSite
  #   subtitle: "This is subtitle"
  #   imageUrl: "<img location>"
  #   imageWidth: 120
  #   imageHeight: 120
  #   imageTitle: my image
  #   buttons:
  #     - name: Posts
  #       url: posts
  #     - name: Tags
  #       url: tags

  # home-info mode
  # home_info_params:
  #   title: "OFA: Towards Unified AI Models"
  #   header:
  #     # background: "linear-gradient(36deg, var(--hero1) 0%, var(--hero2) 80%);"
  #     background_images: "/image/outpainting-home-right-optimized.jpg"
  #     gradient: false
  #   # content: Welcome to my blog

  # social_icons:
  #   # - name: twitter
  #   #   url: "https://twitter.com/"
  #   # - name: stackoverflow
  #   #   url: "https://stackoverflow.com"
  #   - name: github
  #     url: "https://github.com/OFA-Sys"

  # analytics:
  #   google:
  #     SiteVerificationTag: "XYZabc"
  #   bing:
  #     SiteVerificationTag: "XYZabc"
  #   yandex:
  #     SiteVerificationTag: "XYZabc"

  cover:
    link_full_images: true
    responsive_images: true
    hidden: false # hide everywhere but not in structured data
    hidden_in_list: false # hide on list pages and home
    hidden_in_single: false # hide on single page

  # edit_post:
  #   url: "https://github.com/<path_to_repo>/content"
  #   text: "Suggest Changes" # edit text
  #   append_file_path: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    findAllMatches: false
    minMatchCharLength: 2
    keys: ["title", "summary"]

    threshold: 0.1
    ignoreLocation: false
    location: 0
    distance: 1000
    
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 5
    - identifier: api
      name: Resources
      url: /resources
      weight: 10
    - identifier: blog
      name: Blog
      url: /blog/
      weight: 20
    # - identifier: publication
    #   name: Publication
    #   url: /publication
    #   weight: 30
    - identifier: about
      name: About
      url: /about
      weight: 30
    # - identifier: search
    #   name: SEARCH
    #   url: /search
    #   weight: 50
    # - identifier: categories
    #   name: CATEGORIES
    #   url: /categories/
    #   weight: 10
    # - identifier: tags
    #   name: TAGS
    #   url: /tags/
    #   weight: 20
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  goldmark:
    renderer:
      unsafe: true
    extensions:
      footnote: true
  highlight:
    style: vs
    noClasses: false
    # anchorLineNos: true
    codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai
outputs:
    home:
        - HTML
        - JSON # is necessarylog